README.rst
mathics_scanner/data/named-characters.yml

Starting to note down whatever came up in discussion. 
I encourage you to add notes too before we forget all of this and lose what might be useful information in the future.

Start indicating why we chose what we chose.

---

mathics_scanner/characters.py

The original path separator only support *nix. Fix path separator issue for windows platform.

Fix path separator.

---

Makefile
docs/Makefile
docs/make.bat
docs/source/api.rst
docs/source/conf.py
docs/source/implementation.rst
docs/source/index.rst
docs/source/usage.rst
implementation.rst
mathics_scanner/__init__.py
mathics_scanner/characters.py
mathics_scanner/feed.py
mathics_scanner/generate/rl_inputrc.py
mathics_scanner/tokeniser.py

This is a follow up to https://github.com/Mathics3/mathics-scanner/pull/11#issuecomment-774498520. Feel free to improve the documentation as you wish. After this is merged someone should hook things up with readthedocs, I don't know how to do that.

Fix the documentation

---

mathics_scanner/data/named-characters.yml
test/test_general_yaml_sanity.py

Will eventually get used in TeXForm and in formating LaTeX documentation

Start adding AMSLaTeX symbols

---

mathics_scanner/__init__.py
mathics_scanner/characters.py
mathics_scanner/errors.py
mathics_scanner/feed.py
mathics_scanner/load.py
mathics_scanner/prescanner.py
mathics_scanner/tokeniser.py
mathics_scanner/version.py
setup.py
test/test_tokeniser.py

@rocky I tried to change Token to NamedTuple but it didn't increased the performace enough to worth the memory usage increase.
So I just added some type annotations and reformat to keep the same style in all files.

Reformat and add some type annotations

---

Makefile
test/test_tokeniser.py

Convert CamelCase to conventional python test names
alphabetize tests in test_tokenizer
Add targets for running mathics and full tests

Go over unit tests

---

mathics_scanner/data/named-characters.yml

Remove wl-unicode name of Tilde (also known as Infix)

---

mathics_scanner/prescanner.py
test/test_prescanner.py

improves how \ is handled in the prescanner

---

mathics_scanner/prescanner.py
test/test_prescanner.py

support for 32-bit unicode characters

---

.github/workflows/mathics.yml
admin-tools/make-tables.sh
mathics_scanner/data/named-characters.yml
mathics_scanner/generate/build_tables.py
mathics_scanner/tokeniser.py
mathics_scanner/version.py
setup.py
test/test_ascii.py

This adds conversion tables from ASCII operators to unicode symbols. 
These will be used in a branch of the same name in mathics-core.

Revise to add ascii operator tables

---

.github/workflows/mathics.yml
.github/workflows/osx.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
CHANGES.rst
mathics_scanner/data/named-characters.yml
mathics_scanner/feed.py
mathics_scanner/generate/build_tables.py
mathics_scanner/generate/rl_inputrc.py
mathics_scanner/tokeniser.py
mathics_scanner/version.py
setup.py

Last small changes to make release 1.3.0 happen. 
* version bumped
* CHANGES gone over
* CI upgraded
* small spelling corrections.

Release 1.3.0

---

admin-tools/pyenv-versions
setup.py

<strike>In ubuntu - add 3.12 testing</strike>
In local versions remove unsupported version and use latest version for supported versions

Bump testing versions

---

.pre-commit-config.yaml

This seems to fix https://github.com/Mathics3/mathics-core/pull/1013#issuecomment-1959279448 @rocky

.pre-commit-config.yaml: Update using 'pre-commit autoupdate'

---

.github/workflows/autoblack.yml
.pre-commit-config.yaml

Add black and sort checks to match .pre-commit.yaml hooks

black and isort mess

---

pyproject.toml
setup.py

setup.py cleanup

---

.pre-commit-config.yaml
CHANGES.rst
ChangeLog-spell-corrected.diff
Makefile
admin-tools/pyenv-versions
docs/source/conf.py
mathics_scanner/__init__.py
mathics_scanner/feed.py
mathics_scanner/tokeniser.py
mathics_scanner/version.py
pyproject.toml
setup.py

Release 1.3.1

---

mathics_scanner/data/named-characters.yml
test/test_general_yaml_sanity.py
test/test_urls.py

Add URL links to named characters when they exist.  test program test_urls.py will retrieve and check these, but it is very slow. So this test is only run on demand.

Add WL Named Character URLs

---

mathics_scanner/data/named-characters.yml
test/test_general_yaml_sanity.py
test/test_urls.py

Start adding Unicode references

---

mathics_scanner/data/operators.yml
mathics_scanner/generate/build_operator_tables.py
test/test_operators.py

Also, update "meaningful" field comment.

Include no-meaning operators in JSON op extraction

---

mathics_scanner/tokeniser.py

Another round of slight changes, to allow reloading the tables in the tokenizer module.

allows to reload the tables in tokenizer module

---

mathics_scanner/feed.py
mathics_scanner/tokeniser.py
test/test_string_tokens.py
test/test_tokeniser.py

The lint-like change in PR #108 
feed.py: lint and fix types
test/test_string_tokens.py: Split out string token test from other test_tokeniser.py which is getting large. Add more string token tests.

Lint portion of PR #108

---

mathics_scanner/generate/build_tables.py
test/test_character_table_consistency.py
test/test_unicode.py

Add unicode-to-amslatex table and test ASCII-ness in tables that need to be ASCII

Add unicode-to-amslatex table and more testing

---

mathics_scanner/data/named-characters.yml
mathics_scanner/generate/build_tables.py
test/test_general_yaml_sanity.py

This is needed to make the documentation work again.

Complete more amslatex fields

---

mathics_scanner/data/named-characters.yml

more amslatex

---

FUTURE.rst
MANIFEST.in
pyproject.toml
setup.py

* Add a future for this project! (`FUTURE.rst`)
* Miscellaneous packaging changes based on `pyodide build` warnings.

Release stuff

---

.github/workflows/pyodide.yml
.github/workflows/ubuntu.yml
.gitignore
.pre-commit-config.yaml
CHANGES.rst
ChangeLog-spell-corrected.diff
Makefile
README.rst
mathics_scanner/version.py

Get ready for release 1.4.0

---

mathics_scanner/data/named-characters.yml
mathics_scanner/generate/build_tables.py

Start adding comments regarding character uses.

Correct field name in table generation

---

.github/workflows/mathics.yml

Changes have been merged from branch.

Go back to using master branch of mathics-core
