Mathics3/mathics-scanner

- mathics_scanner/errors.py
- mathics_scanner/feed.py
- mathics_scanner/tokeniser.py
This is a follow up to https://github.com/Mathics3/mathics-scanner/issues/9. I documented everything I could find about the bits of the tokeniser used by core.
> Document the tokeniser

- .github/workflows/osx.yaml
- Makefile
- README.rst
- mathics_scanner/data/named-characters.yml
- mathics_scanner/generate/build_tables.py
- mathics_scanner/load.py
- mathics_scanner/version.py
- requirements-dev.txt
- setup.py
- test/test_general_yaml_sanity.py
- test/test_has_unicode_inverse_sanity.py
- test/test_letterlikes_sanity.py
- test/test_table_consistency.py
- test/test_wl_to_ascii.py
- test/util.py
Note: use WL name when there is no conflict for name of symbol.
A number of other small corrections:
- Mark some symbols which are invertable when they are. However
this should be redone and invertability should be detected
automatically.
- small correction in macos CI
- AUTHORS.txt reduced to those who worked in this, rather than Mathics
in general
- in tests prefer top-level tests when that is possible (i.e. test is
not parameterized)
- use relative import as "test" can be ambiguous and lead to namespace problems
> Start tagging operators

- .github/workflows/windows.yml
- mathics_scanner/data/named-characters.yml
- mathics_scanner/generate/.gitignore
- mathics_scanner/generate/build_tables.py
- requirements-dev.txt
- test/test_general_yaml_sanity.py
These add the `unicode-operator` field to indicate which Unicode symbols are binary operators with no built-in meaning. 
These are used in mathics-pygments.
> Tables for pygments

- setup.py
Use SPDX[1] license identifier for portable packaging.
[1] https://spdx.org/licenses/
> Update setup.py: Use SPDX identifier for license

- mathics_scanner/data/named-characters.yml
- mathics_scanner/tokeniser.py
This recognizes the recently added \u21A6 an operator for `Function`. 
However the ASCII equivalent `|->` still is broken.
> Accept \u21A6 as symbol for Function.

- .github/workflows/mathics.yml
- mathics_scanner/data/named-characters.yml
- mathics_scanner/tokeniser.py
* tokeniser.py: include unicode value in addition to WL custom value
* named-characters.yml: note Transpose, Conjugate, and ConjugateTranspose are operators
In the future though we want to break out *what* kind of operator, e.g postfix, prefix, infix
> Corrections/additions to Transpose and Conjugate

- mathics_scanner/data/named-characters.yml
@rocky the precedence of these operators is correct in mathics-core (I checked it in Wolfram Cloud) so I wanted to check if this works if we add the precedence here too.
> Add precedence to the operators ==, != and //

- mathics_scanner/prescanner.py
- mathics_scanner/tokeniser.py
- test/test_prescanner.py
Reduce the use of "self" variables as for local temporary variables. Make private the private functions (try_xxx()).
I don't know why something like "escape sequence" replacement has to be over bloated into the less meaningful and vague "prescanning". Maybe one day it will do something fancier.
> Comment and (type) annotate "prescanning" module.

- mathics_scanner/characters.py
- mathics_scanner/data/named-characters.yml
- mathics_scanner/generate/build_tables.py
- mathics_scanner/tokeniser.py
- test/test_ascii.py
- test/test_general_yaml_sanity.py
- test/test_has_unicode_inverse_sanity.py
- test/test_table_consistency.py
- test/test_tokeniser.py
- test/test_translation_regressions.py
- test/test_unicode_equivalent.py
Go over character tables
* Separate entries with a blank line
*  Remove "unicode-equivalent" when it is the same as "ascii"
Because of this, `wl_to_unicode()` needs to use "ascii" when there is no unicode-equivalent, but  "has-unicode-inverse" is set.
* Add test that unicode-equivalent isn't the same things as ascii
* Include ASCII operators in tables
* Correct DifferentialD unicode - it was correct in master .   Note: \U0001D451 != \u1d451
* Add conversion table `ascii-operator-to-name` to convert an ASCII operator to its WMA name
> Amstext+wl unicode convert

- .github/workflows/osx.yml
- .pre-commit-config.yaml
- mathics_scanner/data/named-characters.yml
- mathics_scanner/errors.py
- mathics_scanner/feed.py
- mathics_scanner/tokeniser.py
- setup.py
* add isort hook and use it
* run codespell over code
* start adding more annotation types
* Python 3.6 no longer supportable. (It doesn't have `re.Match` like newer versions do.
> Administrivia:

- mathics_scanner/generate/build_tables.py
- pyproject.toml
- setup.cfg
- setup.py
- test/test_general_yaml_sanity.py
> Modernize Python metadata

- mathics_scanner/data/named-characters.yml
- mathics_scanner/data/operators.yml
@rljacobson  here are your heuristics added as comments to named-characters.yml
> Add rljacobson's heursitic on Unicode

- mathics_scanner/feed.py
Historically mathics-core's trace function hook call back took a string; encoded in that was a line number.
This keeps the line number and text separate. In the Debugger this is more useful and allows for more semantic information to be passed as well as allows for formatting the line number and the text differently.
> split arguments in trace_fn()

- mathics_scanner/data/named-characters.yml
- mathics_scanner/data/operators.yml
- mathics_scanner/generate/build_operator_tables.py
Most of the information we will need in mathics-core to revise `mathics.core.parser.operators`.
> More operator tables

- .github/workflows/mathics.yml
operator-info-from-JSON merged to master a while ago, so  mathics testing use github master.
> Go back to testing using Mathics core master

- test/testprecedence.m
This PR just adds a WL package to help check if the Precedence values reported by symbols are consistent with the one reported by calling `Precedence` or `WolframLanguageData`, and with the values we use. We can use the functions in the package both in WMA and in Mathics.
> Add precedence test tool

- test/test_mathics_precedence.py
In this PR 
* a more detailed explanation of the goal of the tests and how was designed is included in the docstrings
* The test for the numerical coincidence of `Precedence` against WMA was removed.
* The name of the module constant that holds the ordered list of symbols was changed to a more Non-Yoda-English compatible form.
> Improving docstrings

- .github/workflows/mathics.yml
- mathics_scanner/data/operators.yml
- test/test_mathics_precedence.py
This PR sets the value of `UndirectedEdge` and `DirectedEdge` to 295. This value is the one reported in WMA by `Precedence`, and is compatible with the way in which expressions are parsed and formatted in WMA:
```
In[1]:=  Print["Precedences from Precedence[_]:"];
Print[ Table[op ->  Precedence[op], {op, {TildeTilde, UndirectedEdge, DirectedEdge,   SquareUnion}}]];
Print["Parsing:"];
(*Compare with the way in which expressions involving the operators are parsed:*)
Print["UndirectedEdge and DirectedEdge has higher precedence than TildeTilde:"];
Print[a \[TildeTilde] b \[UndirectedEdge] c, "  parsed as  ",   FullForm[a \[TildeTilde] b \[UndirectedEdge] c]];
Print[a \[UndirectedEdge] b \[TildeTilde] c, "  parsed as  ",   FullForm[a \[UndirectedEdge] b \[TildeTilde] c]];
Print[a \[TildeTilde] …
```
> Precedence for Directed and Undirected Edge

- mathics_scanner/feed.py
- mathics_scanner/prescanner.py
- mathics_scanner/tokeniser.py
- test/test_string_tokens.py
- test/test_tokeniser.py
Handle backslash better...
Recognize special escape characters \n, \t, \r, etc., but disallow other characters.
feed.py: lint and fix types
test/test_string_tokens.py: Split out string token test from other test_tokeniser.py which is getting large. Add more string token tests.
> String tokenization fix

- mathics_scanner/data/operators.yml
- mathics_scanner/tokeniser.py
FractionBox omission was noticed via the new box parsing work.
A slightly nicer repr() for Token - we make clear which parts (tag, text) are strings.
The other changes are more to complete a little more of the prior unfinished work.
> Correct FractionBox and other small changes

- mathics_scanner/data/named-characters.yml
Remove note 5 which is was wrong, and probably comes from the days when I was combining operators with character symbols which is wrong.
Possibly in the future this will be reworked so Operators (like Put) are removed. But this needs to be done in conjunction with the scanner.
> amslatex(Vertial) -> \smallmid. Add more unicode references.

- mathics_scanner/data/named-characters.yml
This completes the amslatex field for all the operator-like symbols. Also replaces the use of double quotes with escape characters whenever it is possible.
> More amslatex

- mathics_scanner/tokeniser.py
- test/test_feed.py
- test/test_tokeniser.py
Note: this was seen in Rubi.m line 215. And also FeynCalc FCMain.m  line 362.
> Treat \ before newline as whitespace.
